import { c as _c } from "@zodiaceco/sdk";
import type * as types from "./types";
import { ref as _ref } from "./ref";
import { allow as _allow } from "./allow";
import { constellation as _constellation } from "./constellation";

declare global {
  // `AllowKit` is augmented by `.zodiac/allow.d.ts` (regenerated by `bun pull-contracts`).
  var allow: typeof _allow;
  var constellation: typeof _constellation;
  var c: typeof _c;
  type Permissions = types.Permissions;
  type Members = types.Members;
  type Specification = types.Specification;
  var ref: typeof _ref;
}

globalThis.allow = _allow;
globalThis.constellation = _constellation;
globalThis.c = _c;
globalThis.ref = _ref;
